### ISSUE TITLE
How convert string to hash?

### ISSUE THREAD

**Issue by ahvahsky2008** [pgrho/phash#13]
I have computed hash 

`0x5065FF62413C004F4B4F7948484D2B53554662494C45344E56565A4C4F4D415153525B4C4C4F4651`

How convert it to Digest?

**Comment by pgrho** [comment]
Its `0x` prefix indicates that it is a hexadecimal integer. So, following 80 chars should be understood as 40 bytes. These bytes can be set to `Digest.Coefficients`.

**Comment by jichaopo** [comment]
I have computed DctHash

3563442159036397554
1802358248218496847

How to compare them

**Comment by Radzhab** [comment]
Add its to DigitHash and compxare
