### ISSUE TITLE
The value range of GetCrossCorrelation

### ISSUE THREAD

**Issue by scegg** [pgrho/phash#15]
should it be inside [0,1]?

**Comment by pgrho** [comment]
Yes.

Mathematically, the cross-correlation itself can be negative. But phash is using unsigned byte vector. So products of any vector components cannot be negative.

**Comment by scegg** [comment]
Thanks.

Is the value linear?
e.g. 0.05 means 5% of pixels are different?

**Comment by pgrho** [comment]
No. It's a cross-correlation based on components that represents a feature of the certain angle.

**Comment by scegg** [comment]
Thanks a lot.
