### ISSUE TITLE
The rate for misjudge of this algorithm is too high

### ISSUE THREAD

**Issue by scegg** [pgrho/phash#16]
I know this is not your fault but pHash.

I test this algorithm in around 500 game CG libraries. When the cross correlation is higher than 0.95, still 10% of the similar files cannot be detected and more than 85% detected items are actually nothing like each other.

Maybe this algorithm is really not a good choice for some kind of pictures.

**Comment by pgrho** [comment]
As pHash depends on small vector calculated from grayscale image, many features of the original image are ignored.
So I think it should be combined with other algorithms. (But I have no idea what method to use)

**Comment by scegg** [comment]
Have no idea either. BTW, I'm writing a program based on your solution, https://github.com/scegg/ImageStore
Still need several days for finishing docs.
