### ISSUE TITLE
Reference System.Drawing.Common instead of CoreCompat.System.Drawing.v2

### ISSUE THREAD

**Issue by fr4gles** [pgrho/phash#17]
Hi, 

As mentioned in title, please consider changing reference from `CoreCompat.System.Drawing.v2` to `System.Drawing.Common` for `.NETStandard 2.0` dependencies because:
- `CoreCompat.System.Drawing.v2` still in preview
- `System.Drawing.Common` is official implementation from MS with source code avilable here: https://github.com/dotnet/corefx/tree/master/src/System.Drawing.Common
- refereing to `CoreCompat.System.Drawing.v2` causing problem when already using `System.Drawing.Common` - like: `The type 'Image' exists in both 'CoreCompat.System.Drawing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`
- As I see project `CoreCompat.System.Drawing.v2` on github https://github.com/CoreCompat/System.Drawing has been archived (discontinued?)
- `System.Drawing.Common` is cross-plaform: How do you use System.Drawing in .NET Core? https://www.hanselman.com/blog/HowDoYouUseSystemDrawingInNETCore.aspx
- I've created sample solution using code located in https://github.com/pgrho/phash/tree/master/src/Shipwreck.Phash.Bitmaps with `System.Drawing.Common` and it passed all tests

I suggest to change reference and bump major or minor version cause it could be "breaking change"?

**Comment by pgrho** [comment]
I'll publish v0.3 if there is no problem.

**Comment by fr4gles** [comment]
What's the progress of v0.3?

**Comment by pgrho** [comment]
Uploaded v0.3 just now

**Comment by fr4gles** [comment]
Thank you, v0.3 works fine.

**Comment by viveksinghnegi7** [comment]
Getting this error in .NetCore 2.1 in Server but not in Code

[Error] Error : "System.IO.FileNotFoundException: Could not load file or assembly 'System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Drawing.Common, Version=4.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by pgrho** [comment]
@viveksinghnegi7 I'm not sure but I think that something is wrong with your deployment, such as dll specified in `.deps.json` is missing.

**Comment by fr4gles** [comment]
@viveksinghnegi7  try `--force` with dotnet publish 
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21

**Comment by fr4gles** [comment]
or try setting `--self-contained` :)

**Comment by viveksinghnegi7** [comment]
The service is automatically build using team-city. **.deps.json** has references to **System.Drawing.Common**

**Comment by fr4gles** [comment]
You should open new issue cause it is working for me well both locally and remotely on build agent.

**Comment by pgrho** [comment]
@viveksinghnegi7 Or you can ask it to TeamCity support.
