### ISSUE TITLE
Creating a good hash

### ISSUE THREAD

**Issue by developervariety** [pgrho/phash#20]
http://www.hackerfactor.com/blog/index.php?/archives/432-Looks-Like-It.html

With this algorithm, do we have to follow any of those steps?

**Comment by pgrho** [comment]
The algorithm mentioned in *Getting Funky With pHash* is implemented as [`ImagePhash.ComputeDctHash`](https://github.com/pgrho/phash/blob/19db00bdd6e7bef7785ecdf53f57121b0b6bef61/src/Shipwreck.Phash/ImagePhash.cs#L145-L179) (translated from `ph_dct_imagehash`). But `Shipwreck.Phash` lacks *Hamming distance algorithm*.

The other hashing algorithm is quite trivial - just resize and binarization. So it is not implemented in pHash. The average hash can be computed by changing value of `dctImage` variable defined in the `ComputeDctHash` to be `img.Resize(8, 8)`.

**Comment by dev-variety** [comment]
I see that it now supports Hamming Distance?

**Comment by developervariety** [comment]
How exactly does hamming distance work with this?

**Comment by pgrho** [comment]
```
// long otherHash;
var hash = ImagePhash.ComputeDctHash(bitmapSource.ToLuminanceImage());
var distance = ImagePhash.GetHammingDistance(hash, otherHash);  // 0-64 (lower is better)
```

**Comment by dev-variety** [comment]
When will you be updating the NuGet?
