### ISSUE TITLE
Shipwreck.Phash.CrossCorrelation is not compatible with .netstandard2.0

### ISSUE THREAD

**Issue by fr4gles** [pgrho/phash#23]
Nuget package Shipwreck.Phash.CrossCorrelation is not compatible with .netstandard2.0

`Warning	NU1701	Package 'Shipwreck.Phash.CrossCorrelation 0.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.	`

**Comment by pgrho** [comment]
The package exposes `CrossCorrelation.GetCrossCorrelation` method group only, and that functionality is available through `ImagePhash.GetCrossCorrelation` in `Shipwreck.Phash` package. So you should use `Shipwreck.Phash` in almost all case.
