### ISSUE TITLE
Multi-threading example

### ISSUE THREAD

**Issue by developervariety** [pgrho/phash#24]
I'm genuinely confused on how to use the multi-threaded example w/ phash.. any help?

**Comment by pgrho** [comment]
Shipwreck.Phash is single-threaded library and it provides a few unary or binary image operations only. So you must parallelize Phash invocations by yourself.

Therefore, there is no general "multi-threaded example" that can apply in all cases. And I don't want to explain in README.md what [Parallel LINQ](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/parallel-linq-plinq) is.

But if you post troubling code fragment here, I can give some advices.
