### ISSUE TITLE
Best approach to find correct answer

### ISSUE THREAD

**Issue by developervariety** [pgrho/phash#25]
I'm in a crisis w/ pHash once again!

A service I use has been getting a bit harder (CPU terms), and I am trying to automate it the best I could. They have these challenges where you rotate the image until it's correctly standing up. I have about 60,000 hashes calculated of the images, but for some reason, when I add more, the solve rate tends to go bad. A week ago they changed the rotation count to 9, so that is more images to calculate hashes for! Especially when you want to automate it and go as fast as possible.

Alright so let me get to it. I download the image, make it black and white, rotate it `9` (used to be `6`) times by `40` (used to be `51.4`), and then finally save the hash of the image in a list. As it goes thru the events bouncing left and right (event-driven programming), it'll reach the process where it compares the `9` hashes against **correct** hashes. Keep in mind these are 60,000 hashes that are correct and verified before used.

The correct ratio (or as I call it, "solve rate") has been going downhill as I add more hashes or remove hashes. There is no proper balance right now, and I'm in a crisis to get this resolved ASAP!

Sorry for the long paragraph, but what do you suggest I do for a right approach. I'm zipping a few images so you can test yourself along with hash database (JSON file) so whenever you have time, you could look through it.

[pHash.zip](https://github.com/pgrho/phash/files/3564315/pHash.zip)
[models.zip](https://github.com/pgrho/phash/files/3564329/models.zip)

PS: the hashes have `0x` removed by default with this database. I should also mention there are `3` different models. Database hashes were also blacked out before being saved.

**Comment by developervariety** [comment]
I should also mention there are `3` different models. Database hashes were also blacked out before being saved.

[models.zip](https://github.com/pgrho/phash/files/3564329/models.zip)

**Comment by developervariety** [comment]
Let me provide my code/my approach so far.

```csharp
for (int i = 1; i < 9; i++) {
 float rotation = 40 f * i;

 using MemoryStream ms = new MemoryStream(task.latestImage);
 using Bitmap bitmap = (Bitmap) Image.FromStream(ms);

 Digest hash = ImagePhash.ComputeDigest(bitmap.RotateImage(rotation).Black().ToLuminanceImage());
 task.rotatedImages.Add(new Tuple < string, string > ($ "{rotation:f2}", hash.ToString()));
}
```

```csharp
string frame = string.Empty;
string hash = string.Empty;
double score = 0;

foreach((string angle, string imageHash) in task.rotatedImages) {
 Digest rotatedImageDigest = new Digest {
  Coefficients = imageHash.StringToByteArray()
 };

 Parallel.ForEach(Globals.Signatures, savedHash => {
  Digest savedDigest = new Digest {
   Coefficients = savedHash.StringToByteArray()
  };

  double weight = ImagePhash.GetCrossCorrelation(rotatedImageDigest, savedDigest);
  if (!(score < weight)) return;

  score = weight;
  frame = angle;
  hash = imageHash;
 });
}

}
```

**Comment by pgrho** [comment]
I'm not sure what is wrong with your project, but I have to point out that the pHash cross correlation is a rotation tolerant algorithm. So if you want to compare rotated images, the pHash is a wrong choice.

**Comment by developervariety** [comment]
Well I understand, but one image out of the `9` is ALWAYS standing up correctly. Wouldn't that take out the "wrong" (rotated) possible choices?

**Comment by developervariety** [comment]
I'll look into this a bit more, and post my solution. I'm thinking of making the background transparent, and finding a size that keeps most of the models in the center of the image. Then possibly use `phash` or `dhash`.

I'll close this til then, thank you!
