### ISSUE TITLE
Differences with phash reference implementation

### ISSUE THREAD

**Issue by AdrianTsai** [pgrho/phash#26]
Looking at the [phash C++ source](https://github.com/aetilius/pHash), it looks like there are several differences between its reference implementation of the DCT hash and the C# reimplementation here. This isn't a complete list, but just by a reading of the code:

* The reference skips the first DCT coefficient. That is, rather than taking the values of the DCT from (0,0) to (8,8) the reference actually takes the values from (1,1) to (9,9).
* The reference uses the median of the DCT values. This implementation uses the mean.
* This one I'm not sure of, but it appears that FloatImage.Multiply actually performs an element-wise multiplication. Presumably, the DCT requires a *matrix* multiplication here, which is what the reference C++ implementation does.

I am looking at a newer version of phash though (0.9.6) so I wonder whether this is intentional due to implementing an older version of the phash algorithm, or if these are potential bugs.

**Comment by pgrho** [comment]
Oh..

I see the pHash-0.9.4 source recorded in my repo also have these differences. I suppose these mistakes are made in translating CImg invocations.

https://github.com/pgrho/phash/blob/be94a0af9d49e34c7b98ee4e09d454989726dcb4/src/Shipwreck.Phash/pHash.cs#L1260-L1264
