### ISSUE TITLE
Black and white PNG image files not processed correctly

### ISSUE THREAD

**Issue by StephenMcConnel** [pgrho/phash#29]
![TG000301](https://user-images.githubusercontent.com/2228246/79803046-71386400-831e-11ea-9eee-a79aa796eb3e.png)
On Windows, computing a PHash of a black and white (1-bit colormap) PNG file can result in a PHash value of all zeroes.
On Linux, a valid looking PHash results, but I don't trust it because the internal processing of the PNG file to the ByteImage array still results in all of the bytes being set to 16.

**Comment by pgrho** [comment]
The image is not a "black and white image". Its palette contains two colors: `#FF000000` (black) and `#00000000` (transparent black).

![image](https://user-images.githubusercontent.com/18061424/79814579-96c67b80-83b9-11ea-852a-54ba3d56c767.png)

And all built-in conversions to ByteImage are designed to simply ignore the alpha channel. So it is a "black image" in a 24bit color sense.

So you should change background-color before creating `ByteImage`, or implement custom translation to treat the alpha channel properly.
