### ISSUE TITLE
pHash of white images

### ISSUE THREAD

**Issue by andhe27** [pgrho/phash#30]
I have to identical white images (see attachment). Generating the pHash i get two identical hash values as well. 
If i compare those two I expect a similarity of 1 (cross correlation). Unfortunately I get 0 as result? Is there a problem with completely white images? 

![image](https://user-images.githubusercontent.com/44060087/87795949-062cf980-c849-11ea-8fb2-e3a9e6eb393f.JPG)

**Comment by pgrho** [comment]
As the cross-correlation calculation is based on a kind of *division*, it doesn't support zero vectors. So the pHash doesn't support single-color-image.
