### ISSUE TITLE
0 Hash on small but still distinct images

### ISSUE THREAD

**Issue by ThatRubenAguilar** [pgrho/phash#5]
It seems once the dimensions of an image get small enough (even around the 300~ range) in one dimension, the base phash will return a 0 Digest for certain images. [This image](https://drive.google.com/open?id=1Yjq-S-Qj9m7HWRcCJSvxPIt8Eylk1WzP) is an example of the behavior (It is merely a crop of the test image).

I'll be going through the original paper and checking the implementation, but one thing I saw as maybe off was [this line.](https://github.com/pgrho/phash/blob/master/src/Shipwreck.Phash/ImagePhash.cs#L237) The parameter is called regionWidth but takes the degrees of lines.

**Comment by pgrho** [comment]
Corresponding lines in the original pHash.cpp goes like:

```cpp
projs.R = new CImg<uint8_t>(N,D,1,1,0);
projs.nb_pix_perline = (int*)calloc(N,sizeof(int));
```

So it seems to be ok.

I think that `Projections.PixelsPerLine` contains some zeros. And these dividers are producing NaNs.

https://github.com/pgrho/phash/blob/master/src/Shipwreck.Phash/ImagePhash.cs#L315

I think it may be ok to simply exclude these zeros from the mean/variance, and set 0 to the feature vector component. But I'm not sure.

**Comment by ThatRubenAguilar** [comment]
Sheesh, this has been a busy 2 weeks. I finally got back around to this. I verified the fix works and went over the implementation as well. Both look pretty good. 

I did have one performance concern in [Operations.](https://github.com/pgrho/phash/blob/master/src/Shipwreck.Phash/Imaging/ByteImageHelper.cs#L13) 
Here we're using an activator to create an instance of a generic type that has no internal state and doesn't use the generic type information. It seems like the generic type could be dropped from [ByteImageOperations](https://github.com/pgrho/phash/blob/master/src/Shipwreck.Phash/Imaging/ByteImageOperations.cs) and replace the activator with either a new or just returning a static variable. Activator is pretty expensive.

**Comment by pgrho** [comment]
As the first step of the `ComputeDigest` (gaussian blur) will call `IByteImage.get_Item(int,int)` 49 times per pixel, I introduced `ByteImageOperations<T>` and provides struct types for `T` to avoid these virual calls. That will generate `T` specific `ByteImageOperation` implementations. I think one `Activator.CreateInstance` is faster than `49 * N` virtual calls. But not sure.

**Comment by ThatRubenAguilar** [comment]
All perf discussions should end in data, so I added some perf harness and ran it with 3 scenarios (Activator, Interface, and Cached Activator) and here were the results:

```
Activator:
Performance Report:
-----
    Digest: {Entries:9200, Min:00:00:00.0834465, Max:00:00:01.0047012, Avg:00:00:00.2990000, Sum:00:45:49.5300000}
-----
    Digest Iteration: {Entries:100, Min:00:00:03.5276470, Max:00:00:04.5452470, Avg:00:00:03.6800000, Sum:00:06:08.0030000}
-----
    Total: {Entries:1, Min:00:06:13.6897875, Max:00:06:13.6897875, Avg:00:06:13.6890000, Sum:00:06:13.6890000}
-----END------

Interface:
Performance Report:
-----
    Digest: {Entries:9200, Min:00:00:00.1382064, Max:00:00:01.6483680, Avg:00:00:00.5160000, Sum:01:19:09.5530000}
-----
    Digest Iteration: {Entries:100, Min:00:00:06.0358392, Max:00:00:06.7233938, Avg:00:00:06.3430000, Sum:00:10:34.2810000}
-----
    Total: {Entries:1, Min:00:10:39.9044135, Max:00:10:39.9044135, Avg:00:10:39.9040000, Sum:00:10:39.9040000}
-----END------

Cached Activator:
Performance Report:
-----
    Digest: {Entries:9200, Min:00:00:00.0909333, Max:00:00:00.9909562, Avg:00:00:00.2980000, Sum:00:45:42.0700000}
-----
    Digest Iteration: {Entries:100, Min:00:00:03.5237442, Max:00:00:03.8664252, Avg:00:00:03.6770000, Sum:00:06:07.6990000}
-----
    Total: {Entries:1, Min:00:06:13.3096289, Max:00:06:13.3096289, Avg:00:06:13.3090000, Sum:00:06:13.3090000}
-----END------

IByteImageWrapper Passthrough:
Performance Report:
-----
    Digest: {Entries:9200, Min:00:00:00.0786959, Max:00:00:00.9199987, Avg:00:00:00.2880000, Sum:00:44:12.8090000}
-----
    Digest Iteration: {Entries:100, Min:00:00:03.4514929, Max:00:00:03.6966232, Avg:00:00:03.5510000, Sum:00:05:55.0880000}
-----
    Total: {Entries:1, Min:00:06:00.5162364, Max:00:06:00.5162364, Avg:00:06:00.5160000, Sum:00:06:00.5160000}
-----END------
```

Activator is indeed faster than the Interface calls by quite a bit. I added a type cache which should see more speed up as the calls increase in the latest [PR](https://github.com/pgrho/phash/pull/8). (The project I am using this for does around 200 comparisons of 600 x 600 images per frame at 20 fps in an interactive application)

**Comment by pgrho** [comment]
Merged the PR and uploaded [Shipwreck.Phash](https://www.nuget.org/packages/Shipwreck.Phash/0.2.1) to nuget.org.
